// =============================================================================
// Module:   SqlOptima.SchemaCompare.Services.DeployScriptBuilder
// Purpose:  Builds self-contained deployable SQL from a compare run folder, separating auto/safe changes from manual-review scripts.
// Author:   Ravi Sharma
// Created:  2026-05-22
// Copyright (c) 2026 Ravi Sharma
// SPDX-License-Identifier: MIT
// =============================================================================

using System.Text;
using System.Text.RegularExpressions;

namespace SqlOptima.SchemaCompare.Services;

/// <summary>
/// A manual script that must be reviewed / executed by a human.
/// </summary>
public sealed class DeployManualFile
{
    public string FileName { get; set; } = "";
    public string FullPath { get; set; } = "";
    public string Content { get; set; } = "";
}

/// <summary>
/// Deployable artefacts for a single destination database: a self-contained
/// (inlined, no <c>:r</c> includes) auto script plus any manual scripts.
/// </summary>
public sealed class DeployDatabaseScript
{
    public string Database { get; set; } = "";
    public string Folder { get; set; } = "";
    public int AutoFileCount { get; set; }

    /// <summary>Fully inlined, ready-to-run T-SQL for the safe/auto changes.</summary>
    public string AutoDeployText { get; set; } = "";

    public List<DeployManualFile> ManualFiles { get; } = new();
}

/// <summary>
/// The complete set of deployable scripts produced from a compare run folder.
/// </summary>
public sealed class DeployScriptResult
{
    public List<DeployDatabaseScript> Databases { get; } = new();

    public bool HasAuto => Databases.Any(d => d.AutoFileCount > 0);
    public bool HasManual => Databases.Any(d => d.ManualFiles.Count > 0);
    public int ManualFileCount => Databases.Sum(d => d.ManualFiles.Count);
    public int AutoFileCount => Databases.Sum(d => d.AutoFileCount);

    /// <summary>
    /// One self-contained script for every destination database, ready to be
    /// executed on the target server (SSMS or sqlcmd, no <c>:r</c> includes).
    /// </summary>
    public string BuildCombinedDeployScript()
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* ============================================================");
        sb.AppendLine(" *  SQL OPTIMA - DEPLOYABLE SYNC SCRIPT (auto / safe changes)");
        sb.AppendLine(" *  Generated by the Schema Compare GUI.");
        sb.AppendLine($" *  Destination databases : {Databases.Count}");
        sb.AppendLine($" *  Auto change scripts    : {AutoFileCount}");
        if (HasManual)
        {
            sb.AppendLine($" *  Manual scripts         : {ManualFileCount}  <-- NOT included here.");
            sb.AppendLine(" *  WARNING: Manual scripts require human review. Run them separately");
            sb.AppendLine(" *           (see the 'Manual actions' tab / manual_*.sql files).");
        }
        sb.AppendLine(" *  This file is self-contained: run it directly on the TARGET server.");
        sb.AppendLine(" *  Never run it against the source database.");
        sb.AppendLine(" * ============================================================ */");
        sb.AppendLine();

        if (!HasAuto)
        {
            sb.AppendLine("-- No automatic (safe) changes were produced. Schemas may already match,");
            sb.AppendLine("-- or every difference requires a manual script (see manual scripts).");
            return sb.ToString();
        }

        foreach (var db in Databases.Where(d => d.AutoFileCount > 0))
        {
            sb.AppendLine("/* ------------------------------------------------------------");
            sb.AppendLine($" *  DATABASE: {db.Database}   ({db.AutoFileCount} auto script(s))");
            sb.AppendLine(" * ------------------------------------------------------------ */");
            sb.AppendLine();
            sb.AppendLine(db.AutoDeployText.TrimEnd());
            sb.AppendLine();
            sb.AppendLine("GO");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    /// <summary>
    /// A single document collecting every manual script with a prominent
    /// warning so the operator knows these must be applied by hand.
    /// </summary>
    public string BuildManualScript()
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* ############################################################");
        sb.AppendLine(" #  MANUAL ACTION REQUIRED - DO NOT RUN BLINDLY");
        sb.AppendLine(" #");
        sb.AppendLine(" #  The changes below could not be applied automatically because");
        sb.AppendLine(" #  they are potentially destructive or ambiguous (e.g. primary key");
        sb.AppendLine(" #  changes, data-type narrowing, identity changes).");
        sb.AppendLine(" #");
        sb.AppendLine(" #  Review each statement, take a backup, and execute manually on");
        sb.AppendLine(" #  the TARGET server after validating impact.");
        sb.AppendLine($" #  Total manual scripts: {ManualFileCount}");
        sb.AppendLine(" ############################################################ */");
        sb.AppendLine();

        if (!HasManual)
        {
            sb.AppendLine("-- No manual scripts were produced for this run.");
            return sb.ToString();
        }

        foreach (var db in Databases.Where(d => d.ManualFiles.Count > 0))
        {
            sb.AppendLine($"/* ===== DATABASE: {db.Database} — {db.ManualFiles.Count} manual script(s) ===== */");
            sb.AppendLine();
            foreach (var m in db.ManualFiles)
            {
                sb.AppendLine($"-- >>> MANUAL: {m.FileName}");
                sb.AppendLine(m.Content.TrimEnd());
                sb.AppendLine();
                sb.AppendLine("-- <<< end manual script");
                sb.AppendLine();
            }
        }
        return sb.ToString();
    }
}

/// <summary>
/// Turns a compare run folder into self-contained, deployable SQL by inlining
/// the <c>:r</c> includes referenced by each <c>_master_auto_only.sql</c>.
/// </summary>
public static class DeployScriptBuilder
{
    private static readonly Regex IncludeLine =
        new(@"^\s*:r\s+(?<file>\S+)\s*$", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    private static readonly Regex DatabaseHeader =
        new(@"Database\s*:\s*(?<db>\S+)", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    public static DeployScriptResult Build(string? runFolder)
    {
        var result = new DeployScriptResult();
        if (string.IsNullOrWhiteSpace(runFolder) || !Directory.Exists(runFolder))
            return result;

        var masters = Directory
            .GetFiles(runFolder, "_master_auto_only.sql", SearchOption.AllDirectories)
            .OrderBy(f => f, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (masters.Count > 0)
        {
            foreach (var master in masters)
            {
                var folder = Path.GetDirectoryName(master) ?? runFolder;
                result.Databases.Add(BuildForFolder(folder, master));
            }
            return result;
        }

        // No master runner - fall back to any auto_/manual_ files in the folder tree.
        var folders = Directory
            .GetFiles(runFolder, "auto_*.sql", SearchOption.AllDirectories)
            .Concat(Directory.GetFiles(runFolder, "manual_*.sql", SearchOption.AllDirectories))
            .Select(f => Path.GetDirectoryName(f) ?? runFolder)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(f => f, StringComparer.OrdinalIgnoreCase);

        foreach (var folder in folders)
            result.Databases.Add(BuildForFolder(folder, master: null));

        return result;
    }

    private static DeployDatabaseScript BuildForFolder(string folder, string? master)
    {
        var db = new DeployDatabaseScript
        {
            Folder = folder,
            Database = new DirectoryInfo(folder).Name
        };

        // Determine ordered auto files (prefer the master's include order).
        List<string> autoNames;
        if (master != null && File.Exists(master))
        {
            var masterText = SafeRead(master);
            var dbMatch = DatabaseHeader.Match(masterText);
            if (dbMatch.Success)
                db.Database = dbMatch.Groups["db"].Value.Trim().Trim('[', ']');
            autoNames = ExtractIncludeOrder(masterText);
        }
        else
        {
            autoNames = Directory.GetFiles(folder, "auto_*.sql")
                .Select(Path.GetFileName)
                .Where(n => n != null)
                .Select(n => n!)
                .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        var sb = new StringBuilder();
        foreach (var name in autoNames)
        {
            var path = Path.Combine(folder, name);
            if (!File.Exists(path))
            {
                sb.AppendLine($"-- WARNING: referenced script not found: {name}");
                sb.AppendLine();
                continue;
            }
            var content = SafeRead(path);
            // Belt-and-suspenders: never put DROP TABLE into the deployable auto script.
            if (ContainsDropTable(content))
            {
                db.ManualFiles.Add(new DeployManualFile
                {
                    FileName = name,
                    FullPath = path,
                    Content = content
                });
                continue;
            }
            sb.AppendLine($"-- ===== {name} =====");
            sb.AppendLine(content.TrimEnd());
            sb.AppendLine();
            sb.AppendLine("GO");
            sb.AppendLine();
            db.AutoFileCount++;
        }
        db.AutoDeployText = sb.ToString();

        foreach (var manualPath in Directory.GetFiles(folder, "manual_*.sql")
                     .OrderBy(f => f, StringComparer.OrdinalIgnoreCase))
        {
            var fileName = Path.GetFileName(manualPath);
            if (db.ManualFiles.Any(m => string.Equals(m.FileName, fileName, StringComparison.OrdinalIgnoreCase)))
                continue;
            db.ManualFiles.Add(new DeployManualFile
            {
                FileName = fileName,
                FullPath = manualPath,
                Content = SafeRead(manualPath)
            });
        }

        return db;
    }

    /// <summary>True when the SQL body contains a DROP TABLE statement.</summary>
    public static bool ContainsDropTable(string? sql)
    {
        if (string.IsNullOrWhiteSpace(sql)) return false;
        return Regex.IsMatch(sql, @"\bDROP\s+TABLE\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    }

    /// <summary>
    /// Reads the ordered list of files referenced by active <c>:r file</c> lines
    /// (commented includes such as <c>-- :r ...</c> are ignored).
    /// </summary>
    public static List<string> ExtractIncludeOrder(string masterText)
    {
        var names = new List<string>();
        if (string.IsNullOrEmpty(masterText)) return names;
        foreach (var raw in masterText.Replace("\r\n", "\n").Split('\n'))
        {
            var m = IncludeLine.Match(raw);
            if (m.Success)
                names.Add(m.Groups["file"].Value.Trim());
        }
        return names;
    }

    private static string SafeRead(string path)
    {
        try { return File.ReadAllText(path); }
        catch { return $"-- Could not read {Path.GetFileName(path)}"; }
    }
}
