// =============================================================================
// Module:   SqlOptima.SchemaCompare.Services.DeployScriptBuilder
// Purpose:  Builds self-contained deployable SQL from a compare run folder, separating auto/safe changes from manual-review scripts.
// Author:   Ravi Sharma
// Created:  2026-05-22
// Copyright (c) 2026 Ravi Sharma
// SPDX-License-Identifier: MIT
// =============================================================================

using System.Text;
using System.Text.RegularExpressions;

namespace SqlOptima.SchemaCompare.Services;

/// <summary>
/// A manual script that must be reviewed / executed by a human.
/// </summary>
public sealed class DeployManualFile
{
    public string FileName { get; set; } = "";
    public string FullPath { get; set; } = "";
    public string Content { get; set; } = "";
    /// <summary>Run-order from _manifest.csv when available; otherwise 999.</summary>
    public int Order { get; set; } = 999;
    public string Purpose { get; set; } = "";
    public string ObjectName { get; set; } = "";
}

/// <summary>
/// Deployable artefacts for a single destination database: a self-contained
/// (inlined, no <c>:r</c> includes) auto script plus any manual scripts.
/// </summary>
public sealed class DeployDatabaseScript
{
    public string Database { get; set; } = "";
    public string Folder { get; set; } = "";
    public int AutoFileCount { get; set; }

    /// <summary>Fully inlined, ready-to-run T-SQL for the safe/auto changes.</summary>
    public string AutoDeployText { get; set; } = "";

    public List<DeployManualFile> ManualFiles { get; } = new();
}

/// <summary>
/// The complete set of deployable scripts produced from a compare run folder.
/// </summary>
public sealed class DeployScriptResult
{
    public List<DeployDatabaseScript> Databases { get; } = new();

    public bool HasAuto => Databases.Any(d => d.AutoFileCount > 0);
    public bool HasManual => Databases.Any(d => d.ManualFiles.Count > 0);
    public int ManualFileCount => Databases.Sum(d => d.ManualFiles.Count);
    public int AutoFileCount => Databases.Sum(d => d.AutoFileCount);

    /// <summary>
    /// One self-contained script for every destination database, ready to be
    /// executed on the target server (SSMS or sqlcmd, no <c>:r</c> includes).
    /// </summary>
    public string BuildCombinedDeployScript()
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* ============================================================");
        sb.AppendLine(" *  SQL OPTIMA - DEPLOYABLE SYNC SCRIPT (auto / safe changes)");
        sb.AppendLine(" *  Generated by the Schema Compare GUI.");
        sb.AppendLine($" *  Destination databases : {Databases.Count}");
        sb.AppendLine($" *  Auto change scripts    : {AutoFileCount}");
        if (HasManual)
        {
            sb.AppendLine($" *  Manual scripts         : {ManualFileCount}  <-- NOT included here.");
            sb.AppendLine(" *  WARNING: Manual scripts require human review. Run them separately");
            sb.AppendLine(" *           (see the 'Manual actions' tab / manual_*.sql files).");
        }
        sb.AppendLine(" *  This file is self-contained: run it directly on the TARGET server.");
        sb.AppendLine(" *  Never run it against the source database.");
        sb.AppendLine(" * ============================================================ */");
        sb.AppendLine();

        if (!HasAuto)
        {
            sb.AppendLine("-- No automatic (safe) changes were produced. Schemas may already match,");
            sb.AppendLine("-- or every difference requires a manual script (see manual scripts).");
            return sb.ToString();
        }

        foreach (var db in Databases.Where(d => d.AutoFileCount > 0))
        {
            sb.AppendLine("/* ------------------------------------------------------------");
            sb.AppendLine($" *  DATABASE: {db.Database}   ({db.AutoFileCount} auto script(s))");
            sb.AppendLine(" * ------------------------------------------------------------ */");
            sb.AppendLine();
            sb.AppendLine(db.AutoDeployText.TrimEnd());
            sb.AppendLine();
            sb.AppendLine("GO");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    /// <summary>
    /// A single document collecting every manual script with a prominent
    /// warning so the operator knows these must be applied by hand.
    /// </summary>
    public string BuildManualScript()
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* ############################################################");
        sb.AppendLine(" #  MANUAL ACTION REQUIRED - DO NOT RUN BLINDLY");
        sb.AppendLine(" #");
        sb.AppendLine(" #  The changes below could not be applied automatically because");
        sb.AppendLine(" #  they are potentially destructive or ambiguous (e.g. primary key");
        sb.AppendLine(" #  changes, data-type narrowing, identity changes).");
        sb.AppendLine(" #");
        sb.AppendLine(" #  Review each statement, take a backup, and execute manually on");
        sb.AppendLine(" #  the TARGET server after validating impact.");
        sb.AppendLine($" #  Total manual scripts: {ManualFileCount}");
        sb.AppendLine(" ############################################################ */");
        sb.AppendLine();

        if (!HasManual)
        {
            sb.AppendLine("-- No manual scripts were produced for this run.");
            return sb.ToString();
        }

        var hasPkDatatype = Databases
            .SelectMany(d => d.ManualFiles)
            .Any(m => string.Equals(m.Purpose, "pk_datatype_change", StringComparison.OrdinalIgnoreCase)
                      || m.FileName.Contains("pk_datatype_change", StringComparison.OrdinalIgnoreCase)
                      || m.Content.Contains("PK COLUMN DATATYPE CHANGE", StringComparison.OrdinalIgnoreCase));

        if (hasPkDatatype)
        {
            sb.AppendLine("/* ============================================================");
            sb.AppendLine(" *  PK COLUMN DATATYPE CHANGE — REQUIRED SEQUENCE");
            sb.AppendLine(" *");
            sb.AppendLine(" *  When a primary-key column changes datatype, dependent foreign");
            sb.AppendLine(" *  keys and indexes must be handled first. Each");
            sb.AppendLine(" *  manual_*__pk_datatype_change.sql file already contains this");
            sb.AppendLine(" *  sequence — run that file as one unit (do not reorder steps):");
            sb.AppendLine(" *");
            sb.AppendLine(" *    1) Drop FK constraints that reference the parent PK");
            sb.AppendLine(" *    2) Drop non-PK indexes on the parent that include PK columns");
            sb.AppendLine(" *    3) Drop the parent primary key");
            sb.AppendLine(" *    4) Alter parent PK column(s) to the source datatype");
            sb.AppendLine(" *    5) On each child: drop indexes on FK columns, then alter FK columns");
            sb.AppendLine(" *    6) Recreate the parent primary key from source");
            sb.AppendLine(" *    7) Recreate child indexes, then recreate foreign keys");
            sb.AppendLine(" *");
            sb.AppendLine(" *  Run pk_datatype_change scripts before other manuals / auto");
            sb.AppendLine(" *  scripts that depend on those columns (see _manifest.csv).");
            sb.AppendLine(" * ============================================================ */");
            sb.AppendLine();
        }

        foreach (var db in Databases.Where(d => d.ManualFiles.Count > 0))
        {
            sb.AppendLine($"/* ===== DATABASE: {db.Database} — {db.ManualFiles.Count} manual script(s) ===== */");
            sb.AppendLine();
            foreach (var m in db.ManualFiles.OrderBy(x => x.Order).ThenBy(x => x.FileName, StringComparer.OrdinalIgnoreCase))
            {
                if (!string.IsNullOrWhiteSpace(m.Purpose) || m.Order < 999)
                {
                    sb.AppendLine($"-- >>> MANUAL: {m.FileName}  (order={m.Order}" +
                                  (string.IsNullOrWhiteSpace(m.Purpose) ? "" : $", purpose={m.Purpose}") +
                                  (string.IsNullOrWhiteSpace(m.ObjectName) ? "" : $", object={m.ObjectName}") +
                                  ")");
                }
                else
                {
                    sb.AppendLine($"-- >>> MANUAL: {m.FileName}");
                }

                if (string.Equals(m.Purpose, "pk_datatype_change", StringComparison.OrdinalIgnoreCase)
                    || m.FileName.Contains("pk_datatype_change", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine("--     Run as one unit: drop FKs → drop PK → alter parent → alter children → recreate PK/FKs/indexes");
                }

                sb.AppendLine(m.Content.TrimEnd());
                sb.AppendLine();
                sb.AppendLine("-- <<< end manual script");
                sb.AppendLine();
            }
        }
        return sb.ToString();
    }
}

/// <summary>
/// Turns a compare run folder into self-contained, deployable SQL by inlining
/// the <c>:r</c> includes referenced by each <c>_master_auto_only.sql</c>.
/// </summary>
public static class DeployScriptBuilder
{
    private static readonly Regex IncludeLine =
        new(@"^\s*:r\s+(?<file>\S+)\s*$", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    private static readonly Regex DatabaseHeader =
        new(@"Database\s*:\s*(?<db>\S+)", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    public static DeployScriptResult Build(string? runFolder)
    {
        var result = new DeployScriptResult();
        if (string.IsNullOrWhiteSpace(runFolder) || !Directory.Exists(runFolder))
            return result;

        var masters = Directory
            .GetFiles(runFolder, "_master_auto_only.sql", SearchOption.AllDirectories)
            .OrderBy(f => f, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (masters.Count > 0)
        {
            foreach (var master in masters)
            {
                var folder = Path.GetDirectoryName(master) ?? runFolder;
                result.Databases.Add(BuildForFolder(folder, master));
            }
            return result;
        }

        // No master runner - fall back to any auto_/manual_ files in the folder tree.
        var folders = Directory
            .GetFiles(runFolder, "auto_*.sql", SearchOption.AllDirectories)
            .Concat(Directory.GetFiles(runFolder, "manual_*.sql", SearchOption.AllDirectories))
            .Select(f => Path.GetDirectoryName(f) ?? runFolder)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(f => f, StringComparer.OrdinalIgnoreCase);

        foreach (var folder in folders)
            result.Databases.Add(BuildForFolder(folder, master: null));

        return result;
    }

    private static DeployDatabaseScript BuildForFolder(string folder, string? master)
    {
        var db = new DeployDatabaseScript
        {
            Folder = folder,
            Database = new DirectoryInfo(folder).Name
        };

        // Determine ordered auto files (prefer the master's include order).
        List<string> autoNames;
        if (master != null && File.Exists(master))
        {
            var masterText = SafeRead(master);
            var dbMatch = DatabaseHeader.Match(masterText);
            if (dbMatch.Success)
                db.Database = dbMatch.Groups["db"].Value.Trim().Trim('[', ']');
            autoNames = ExtractIncludeOrder(masterText);
        }
        else
        {
            autoNames = Directory.GetFiles(folder, "auto_*.sql")
                .Select(Path.GetFileName)
                .Where(n => n != null)
                .Select(n => n!)
                .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        var sb = new StringBuilder();
        foreach (var name in autoNames)
        {
            var path = Path.Combine(folder, name);
            if (!File.Exists(path))
            {
                sb.AppendLine($"-- WARNING: referenced script not found: {name}");
                sb.AppendLine();
                continue;
            }
            var content = SafeRead(path);
            // Belt-and-suspenders: never put DROP TABLE into the deployable auto script.
            if (ContainsDropTable(content))
            {
                db.ManualFiles.Add(new DeployManualFile
                {
                    FileName = name,
                    FullPath = path,
                    Content = content
                });
                continue;
            }
            sb.AppendLine($"-- ===== {name} =====");
            sb.AppendLine(content.TrimEnd());
            sb.AppendLine();
            sb.AppendLine("GO");
            sb.AppendLine();
            db.AutoFileCount++;
        }
        db.AutoDeployText = sb.ToString();

        var manifestMeta = ReadManifestMeta(folder);

        foreach (var manualPath in Directory.GetFiles(folder, "manual_*.sql")
                     .OrderBy(f => f, StringComparer.OrdinalIgnoreCase))
        {
            var fileName = Path.GetFileName(manualPath);
            if (db.ManualFiles.Any(m => string.Equals(m.FileName, fileName, StringComparison.OrdinalIgnoreCase)))
                continue;
            db.ManualFiles.Add(new DeployManualFile
            {
                FileName = fileName,
                FullPath = manualPath,
                Content = SafeRead(manualPath)
            });
        }

        foreach (var m in db.ManualFiles)
        {
            if (!manifestMeta.TryGetValue(m.FileName, out var meta)) continue;
            m.Order = meta.Order;
            m.Purpose = meta.Purpose;
            m.ObjectName = meta.ObjectName;
        }

        db.ManualFiles.Sort((a, b) =>
        {
            var cmp = a.Order.CompareTo(b.Order);
            return cmp != 0 ? cmp : string.Compare(a.FileName, b.FileName, StringComparison.OrdinalIgnoreCase);
        });

        return db;
    }

    /// <summary>
    /// Reads Order / Purpose / Object from <c>_manifest.csv</c> keyed by FileName.
    /// </summary>
    internal static Dictionary<string, (int Order, string Purpose, string ObjectName)> ReadManifestMeta(string folder)
    {
        var map = new Dictionary<string, (int Order, string Purpose, string ObjectName)>(StringComparer.OrdinalIgnoreCase);
        var path = Path.Combine(folder, "_manifest.csv");
        if (!File.Exists(path)) return map;

        try
        {
            var lines = File.ReadAllLines(path);
            if (lines.Length < 2) return map;
            var header = ParseCsvLine(lines[0]);
            int Idx(string name)
            {
                for (var i = 0; i < header.Count; i++)
                    if (string.Equals(header[i], name, StringComparison.OrdinalIgnoreCase))
                        return i;
                return -1;
            }

            var iFile = Idx("FileName");
            var iOrder = Idx("Order");
            var iPurpose = Idx("Purpose");
            var iObject = Idx("Object");
            if (iFile < 0) return map;

            for (var li = 1; li < lines.Length; li++)
            {
                if (string.IsNullOrWhiteSpace(lines[li])) continue;
                var cols = ParseCsvLine(lines[li]);
                if (iFile >= cols.Count) continue;
                var fileName = cols[iFile].Trim().Trim('"');
                if (string.IsNullOrWhiteSpace(fileName)) continue;
                var order = 999;
                if (iOrder >= 0 && iOrder < cols.Count && int.TryParse(cols[iOrder].Trim().Trim('"'), out var o))
                    order = o;
                var purpose = iPurpose >= 0 && iPurpose < cols.Count ? cols[iPurpose].Trim().Trim('"') : "";
                var obj = iObject >= 0 && iObject < cols.Count ? cols[iObject].Trim().Trim('"') : "";
                map[fileName] = (order, purpose, obj);
            }
        }
        catch
        {
            // Manifest is advisory; ignore parse failures.
        }

        return map;
    }

    private static List<string> ParseCsvLine(string line)
    {
        var result = new List<string>();
        if (line == null) return result;
        var sb = new StringBuilder();
        var inQuotes = false;
        for (var i = 0; i < line.Length; i++)
        {
            var ch = line[i];
            if (ch == '"')
            {
                if (inQuotes && i + 1 < line.Length && line[i + 1] == '"')
                {
                    sb.Append('"');
                    i++;
                }
                else inQuotes = !inQuotes;
                continue;
            }
            if (ch == ',' && !inQuotes)
            {
                result.Add(sb.ToString());
                sb.Clear();
                continue;
            }
            sb.Append(ch);
        }
        result.Add(sb.ToString());
        return result;
    }

    /// <summary>True when the SQL body contains a DROP TABLE statement.</summary>
    public static bool ContainsDropTable(string? sql)
    {
        if (string.IsNullOrWhiteSpace(sql)) return false;
        return Regex.IsMatch(sql, @"\bDROP\s+TABLE\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    }

    /// <summary>
    /// Reads the ordered list of files referenced by active <c>:r file</c> lines
    /// (commented includes such as <c>-- :r ...</c> are ignored).
    /// </summary>
    public static List<string> ExtractIncludeOrder(string masterText)
    {
        var names = new List<string>();
        if (string.IsNullOrEmpty(masterText)) return names;
        foreach (var raw in masterText.Replace("\r\n", "\n").Split('\n'))
        {
            var m = IncludeLine.Match(raw);
            if (m.Success)
                names.Add(m.Groups["file"].Value.Trim());
        }
        return names;
    }

    private static string SafeRead(string path)
    {
        try { return File.ReadAllText(path); }
        catch { return $"-- Could not read {Path.GetFileName(path)}"; }
    }
}
